### ISSUE TITLE
Favicon meta files not updated by collectstatic

### ISSUE THREAD

**Issue by Kromey** [Kromey/fbxnano#11]
The files manifest.json and browserconfig.xml in htdocs/static/favicon (see 6b80e75d04747ff574edfc3529f00e37393aa379) do not get properly updated when collectfiles is run. Maybe there is a way to hook into that command's method for e.g. updating URLs in CSS files to do the same for these two? Or perhaps better would be to pull these files into a view and use the {% static %} template tag there to properly reference the collectstatic'd files?

**Comment by jonmsawyer** [comment]
> do not get properly updated when **collectfiles** is run

Typo? Don't you mean `collectstatic`?

**Comment by jonmsawyer** [comment]
Is this still a valid and current question? It appears you've already handled `browserconfig.xml` with 581063cdab48d772a744d0284c4718bf234b282f and `manifest.json` with a566ade66b86e5503ec514ba28ae1ae3c72231fd.

**Comment by Kromey** [comment]
You are correct, my good sir! Apparently I forgot to update the issue!
