### ISSUE TITLE
Maintain a "next url" in session or in a cookie when akwriters requires the user to log in

### ISSUE THREAD

**Issue by jonmsawyer** [Kromey/fbxnano#22]
> Maintain a "next url" in request.session or in a cookie when akwriters requires the user to log in.
## Use case

Suppose a friend gives you a link to a protected resource, e.g., https://dev.akwriters.org/auth/app_passwords. `akwriters` will instead redirect you to the log in page and prompt you to log in. Upon entering your email address and the captcha, an email is sent to you. You click the link and you're now signed in, but rather than seeing https://dev.akwriters.org/auth/app_passwords, you see https://dev.akwriters.org/chat/.
## Proposal

Subclass `from django.contrib.auth.mixins import LoginRequiredMixin` and save the request URI and all query string parameters inside of the current user session, a cookie, or persistent querystring parameter before redirecting the user to the log in page. A technique that I use is to base64 encode the string so that you can have a URL safe method for passing this encoded string around either via header, querystring, etc.

Every time a user tries to access a protected resource for which they are not authenticated, the request URI is saved in the same manner. Then, redirect the user to the saved request URI when they log in. This should make it easy to go from one unauthenticated page to another authenticated page without having to go to the authenticated page via extra clicks and navigation.
### Nice to have

When a user clicks on "Login" link, the subclass ought to save the referrer if the referrer domain and page come from the same domain as `akwriters`. Upon authentication, the user should be redirected to the page they were previously on.

**Comment by Kromey** [comment]
The `LoginRequiredMixin` and `login_required` decorator both supply the path of the URL that the user attempted to access in a GET parameter called `next` to the login page. While there's need to ensure that we don't create an open redirect here (to avoid bad guys sending links that look like akwriters URLs but which actually send users to their big bad scary CIA blacksite, it surely can't be too difficult to snag and store that in the session when presenting the login page, and then redirecting to it upon authentication.

**Comment by Kromey** [comment]
This is now implemented.
